SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_PROCESSOR riscv)

SET(CMAKE_ROOT_PATH "/opt/riscv")

SET(CMAKE_ASM_COMPILER "${CMAKE_ROOT_PATH}/bin/riscv64-unknown-elf-gcc")
SET(CMAKE_C_COMPILER "${CMAKE_ROOT_PATH}/bin/riscv64-unknown-elf-gcc")
SET(CMAKE_CXX_COMPILER "${CMAKE_ROOT_PATH}/bin/riscv64-unknown-elf-g++")
SET(RISCV_OBJDUMP "${CMAKE_ROOT_PATH}/bin/riscv64-unknown-elf-objdump")
SET(RISCV_OBJCOPY "${CMAKE_ROOT_PATH}/bin/riscv64-unknown-elf-objcopy")
SET(RISCV_SIZE "${CMAKE_ROOT_PATH}/bin/riscv64-unknown-elf-size")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
